# Generated by Django 3.2.4 on 2021-07-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_auto_20210719_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='Address',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='contactnumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
